"""
AI Transparency Module - EU AI Act Article 52 Compliance

This module provides utilities for AI-generated content disclosure
as required by EU AI Act transparency obligations.
"""

from datetime import datetime
from typing import Optional
import os


# Configuration
AI_TRANSPARENCY_ENABLED = os.getenv("AI_TRANSPARENCY_ENABLED", "true").lower() == "true"
AI_DISCLOSURE_PREFIX = "[AI Generated]"
AI_HEADER_TEMPLATE = '''"""
{disclosure}
Generated by: {agent_name}
Generated at: {timestamp}
Model: {model}

This content was automatically generated by an AI system.
Human review is recommended before production use.
"""

'''


def get_ai_header(
    agent_name: str = "Maestro AI Agent",
    model: str = "Claude",
    disclosure: str = "AI-GENERATED CONTENT"
) -> str:
    """
    Generate AI attribution header for code files.

    Args:
        agent_name: Name of the AI agent that generated the content
        model: AI model used for generation
        disclosure: Disclosure statement

    Returns:
        Formatted header string for insertion at top of files
    """
    if not AI_TRANSPARENCY_ENABLED:
        return ""

    return AI_HEADER_TEMPLATE.format(
        disclosure=disclosure,
        agent_name=agent_name,
        timestamp=datetime.utcnow().isoformat() + "Z",
        model=model
    )


def get_jira_disclosure(message: str) -> str:
    """
    Add AI disclosure prefix to Jira comments.

    Args:
        message: Original message content

    Returns:
        Message with AI disclosure prefix
    """
    if not AI_TRANSPARENCY_ENABLED:
        return message

    return f"{AI_DISCLOSURE_PREFIX} {message}"


def get_confluence_footer() -> str:
    """
    Generate AI disclosure footer for Confluence pages.

    Returns:
        HTML footer for Confluence pages
    """
    if not AI_TRANSPARENCY_ENABLED:
        return ""

    return f'''
<hr/>
<p><em>{AI_DISCLOSURE_PREFIX} This page was generated or modified by an AI system.
Generated at: {datetime.utcnow().isoformat()}Z</em></p>
'''


class AITransparencyConfig:
    """Configuration class for AI transparency settings."""

    def __init__(self):
        self.enabled = AI_TRANSPARENCY_ENABLED
        self.disclosure_prefix = AI_DISCLOSURE_PREFIX
        self.default_agent_name = "Maestro AI Agent"
        self.default_model = "Claude"

    def to_dict(self) -> dict:
        """Export configuration as dictionary."""
        return {
            "enabled": self.enabled,
            "disclosure_prefix": self.disclosure_prefix,
            "default_agent_name": self.default_agent_name,
            "default_model": self.default_model
        }


# Singleton config instance
config = AITransparencyConfig()
