"""AI Disclosure Banner Implementation - EU AI Act Article 52"""
from typing import Dict, Any, Optional
from datetime import datetime
import json

class AIDisclosureBanner:
    """Adds disclosure banners to AI-generated content."""

    DISCLOSURE_TEXT = "[AI-Generated] This content was produced by an AI system."
    DISCLOSURE_HTML = '<div class="ai-disclosure" role="alert" aria-label="AI Generated Content">[AI-Generated] This content was produced by an AI system.</div>'

    def __init__(self, provider: str = "Unknown", model: str = "Unknown"):
        self.provider = provider
        self.model = model
        self.timestamp = datetime.utcnow().isoformat()

    def wrap_text(self, content: str) -> str:
        """Wrap text content with AI disclosure."""
        return f"{self.DISCLOSURE_TEXT}\n\n{content}\n\n---\nGenerated by: {self.provider} ({self.model}) at {self.timestamp}"

    def wrap_html(self, content: str) -> str:
        """Wrap HTML content with AI disclosure banner."""
        return f'{self.DISCLOSURE_HTML}\n{content}'

    def get_metadata(self) -> Dict[str, Any]:
        """Return disclosure metadata for logging."""
        return {
            "ai_generated": True,
            "provider": self.provider,
            "model": self.model,
            "timestamp": self.timestamp,
            "disclosure_version": "1.0",
            "eu_ai_act_article": "52"
        }


def add_ai_disclosure(content: str, provider: str, model: str, format: str = "text") -> Dict[str, Any]:
    """
    Add AI disclosure to content.

    Args:
        content: The AI-generated content
        provider: AI provider name (e.g., "Anthropic", "OpenAI")
        model: Model identifier (e.g., "claude-3", "gpt-4")
        format: Output format ("text" or "html")

    Returns:
        Dict with disclosed content and metadata
    """
    banner = AIDisclosureBanner(provider, model)

    if format == "html":
        disclosed_content = banner.wrap_html(content)
    else:
        disclosed_content = banner.wrap_text(content)

    return {
        "content": disclosed_content,
        "metadata": banner.get_metadata(),
        "original_length": len(content),
        "disclosed_length": len(disclosed_content)
    }
