# Simple Secrets for Minikube Testing
# For development/testing only - NOT for production

# NOTE: In production, use External Secrets Operator with AWS Secrets Manager or Vault

---
# MLflow Secrets
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-credentials
  namespace: ml-platform
type: Opaque
stringData:
  database-password: "mlflow_dev_password_123"
  s3-access-key: "minioadmin"
  s3-secret-key: "minioadmin"
  admin-password: "admin123"

---
# Feast Secrets
apiVersion: v1
kind: Secret
metadata:
  name: feast-credentials
  namespace: ml-platform
type: Opaque
stringData:
  postgres-password: "feast_dev_password_123"
  redis-password: ""  # No password for dev

---
# Airflow Secrets
apiVersion: v1
kind: Secret
metadata:
  name: airflow-credentials
  namespace: airflow
type: Opaque
stringData:
  postgres-password: "airflow_dev_password_123"
  # Generate fernet key: python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
  fernet-key: "gAAAAABfW7mH4FQH8LnMq3vZ6b9Wl0nNsK4eCxVfYZ1234567890abcdefghijk="
  webserver-secret-key: "dev_secret_key_12345"
  admin-password: "admin"
  admin-username: "admin"

---
# PostgreSQL Shared Secrets
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: storage
type: Opaque
stringData:
  postgres-password: "postgres_dev_123"
  postgres-user: "maestro"

---
# Container Registry Secrets
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: registry
type: Opaque
stringData:
  admin-password: "registry_admin_123"

---
# MinIO Secrets
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: storage
type: Opaque
stringData:
  root-user: "minioadmin"
  root-password: "minioadmin123"

---
# Docker Registry Pull Secret (for private images)
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: ml-platform
type: kubernetes.io/dockerconfigjson
data:
  # Base64 encoded: {"auths":{"registry.example.com":{"username":"admin","password":"admin123"}}}
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJhZG1pbjEyMyJ9fX0=

---
# API Keys for External Services
apiVersion: v1
kind: Secret
metadata:
  name: api-keys
  namespace: ml-platform
type: Opaque
stringData:
  openai-api-key: "sk-dev-key-placeholder"
  huggingface-token: "hf-dev-token-placeholder"
  github-token: "ghp-dev-token-placeholder"

---
# TLS Certificate for Ingress (self-signed for dev)
apiVersion: v1
kind: Secret
metadata:
  name: tls-certificate
  namespace: ml-platform
type: kubernetes.io/tls
data:
  # Self-signed cert (generate with: openssl req -x509 -nodes -days 365 -newkey rsa:2048)
  tls.crt: LS0tLS1CRUdJTi... # Base64 encoded cert
  tls.key: LS0tLS1CRUdJTi... # Base64 encoded key

---
# SSH Keys for Git Access
apiVersion: v1
kind: Secret
metadata:
  name: git-ssh-key
  namespace: ml-platform
type: Opaque
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    # Dev SSH key (not for production)
    -----END OPENSSH PRIVATE KEY-----
  known_hosts: |
    github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA...

---
# Database Connection Strings
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: ml-platform
data:
  mlflow-db-url: "postgresql://mlflow:$(MLFLOW_DB_PASSWORD)@postgresql.storage.svc.cluster.local:5432/mlflow_db"
  feast-db-url: "postgresql://feast:$(FEAST_DB_PASSWORD)@postgresql.storage.svc.cluster.local:5432/feast_db"
  airflow-db-url: "postgresql://airflow:$(AIRFLOW_DB_PASSWORD)@postgresql.storage.svc.cluster.local:5432/airflow_db"

---
# Script to generate secrets
# Save as: scripts/generate-dev-secrets.sh
apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-generator-script
  namespace: ml-platform
data:
  generate-secrets.sh: |
    #!/bin/bash
    # Generate development secrets for minikube

    # Generate Fernet key for Airflow
    python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"

    # Generate random password
    openssl rand -base64 32

    # Generate self-signed TLS certificate
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
      -keyout tls.key -out tls.crt \
      -subj "/CN=ml-platform.local/O=Development"

    # Generate SSH key
    ssh-keygen -t rsa -b 4096 -f git_ssh_key -N ""

    # Create Docker config JSON
    echo -n '{"auths":{"localhost:30506":{"username":"admin","password":"admin123"}}}' | base64

    echo "✓ Secrets generated!"
    echo ""
    echo "Next steps:"
    echo "1. Update secrets in infrastructure/minikube/secrets.yaml"
    echo "2. kubectl apply -f infrastructure/minikube/secrets.yaml"
