"""Personas module for Maestro Hive."""

from .team_composer import TeamComposer
from .collaboration_engine import CollaborationEngine
from .persona_registry import PersonaRegistry, PersonaDefinition
from .skill_registry import (
    SkillRegistry,
    SkillDefinition,
    SkillCategory,
    SkillStatus,
    get_skill_registry
)
from .skill_injector import (
    SkillInjector,
    InjectionConfig,
    InjectionResult,
    InjectionMode,
    inject_skill,
    get_skill_injector
)
from .fusion_engine import (
    FusionEngine,
    FusionStrategy,
    FusedPersona,
    FusionConfig,
    FusionPreview,
    FusionValidationResult,
    PersonaTrait,
    FusionCache,
    fuse,
    get_default_engine
)
from .trait_blender import (
    TraitBlender,
    BlendMode,
    ConflictResolution,
    TraitValue,
    BlendResult,
    BlenderConfig,
    blend,
    get_default_blender
)
# MD-3018: Trait Evolution & Guidance
from .trait_manager import (
    TraitManager,
    Trait,
    TraitCategory as TraitCategoryEnum,
    TraitStatus as TraitStatusEnum,
    TraitMetrics,
    TraitEvent,
    TraitValidationError,
    TraitNotFoundError,
    get_trait_manager
)
from .skill_decay_tracker import (
    SkillDecayTracker,
    DecayParameters,
    DecayCalculationResult,
    DecayAlert,
    DecayAlertLevel,
    get_skill_decay_tracker
)
from .evolution_guide import (
    EvolutionGuide,
    EvolutionRecommendation,
    EvolutionPlan,
    CareerGoal,
    LearningResource,
    RecommendationPriority,
    RecommendationType,
    get_evolution_guide
)
# MD-3021: Persona Evolution & Learning
from .learning_engine import (
    LearningEngine,
    Experience,
    ExperienceType,
    ExperienceResult,
    LearningOutcome,
    SkillLevelData,
    LearningStats,
    LearningEngineConfig,
    get_learning_engine,
)
from .evolution_tracker import (
    EvolutionTracker,
    Milestone,
    MilestoneType,
    EvolutionSnapshot,
    EvolutionStage,
    GrowthMetrics,
    EvolutionConfig,
    get_tracker,
    record_skill_update,
    get_evolution_summary,
)
# MD-3026: RAG Persona Integration
from .rag_connector import (
    RAGConnector,
    RAGConfig,
    RAGProviderType,
    QueryStrategy,
    ConnectionStatus,
    EmbeddingVector,
    RetrievalResult,
    RetrievalContext,
    IndexStats,
    get_rag_connector,
    reset_rag_connector,
    retrieve_context,
)
from .context_enhancer import (
    ContextEnhancer,
    EnhancerConfig,
    EnhancementStrategy,
    ContextFormat,
    EnhancementPriority,
    ContextChunk,
    EnhancedPrompt,
    EnhancedResponse,
    get_context_enhancer,
    reset_context_enhancer,
    enhance_prompt,
)
from .knowledge_index import (
    KnowledgeIndexManager,
    IndexConfig,
    IndexStatus,
    Document,
    DocumentType,
    DocumentChunk,
    IndexedDocument,
    IndexingResult,
    IndexHealth,
    ChunkingStrategy,
    get_knowledge_index_manager,
    reset_knowledge_index_manager,
    quick_index,
)
# MD-3090: Persona Memory & Persistence
from .memory_store import (
    MemoryStore,
    Memory,
    MemoryType,
    MemoryStatus,
    MemoryStoreConfig,
    MemoryQueryResult,
    ConsolidationResult,
    ConsolidationStrategy,
    StoreStats,
    HealthStatus,
    get_memory_store,
    reset_memory_store,
    store_memory,
    retrieve_memories,
)

__all__ = [
    "TeamComposer",
    "CollaborationEngine",
    "PersonaRegistry",
    "PersonaDefinition",
    "SkillRegistry",
    "SkillDefinition",
    "SkillCategory",
    "SkillStatus",
    "get_skill_registry",
    "SkillInjector",
    "InjectionConfig",
    "InjectionResult",
    "InjectionMode",
    "inject_skill",
    "get_skill_injector",
    # Fusion Engine (MD-3017)
    "FusionEngine",
    "FusionStrategy",
    "FusedPersona",
    "FusionConfig",
    "FusionPreview",
    "FusionValidationResult",
    "PersonaTrait",
    "FusionCache",
    "fuse",
    "get_default_engine",
    # Trait Blender (MD-3017)
    "TraitBlender",
    "BlendMode",
    "ConflictResolution",
    "TraitValue",
    "BlendResult",
    "BlenderConfig",
    "blend",
    "get_default_blender",
    # Trait Manager (MD-3018)
    "TraitManager",
    "Trait",
    "TraitCategoryEnum",
    "TraitStatusEnum",
    "TraitMetrics",
    "TraitEvent",
    "TraitValidationError",
    "TraitNotFoundError",
    "get_trait_manager",
    # Skill Decay Tracker (MD-3018)
    "SkillDecayTracker",
    "DecayParameters",
    "DecayCalculationResult",
    "DecayAlert",
    "DecayAlertLevel",
    "get_skill_decay_tracker",
    # Evolution Guide (MD-3018)
    "EvolutionGuide",
    "EvolutionRecommendation",
    "EvolutionPlan",
    "CareerGoal",
    "LearningResource",
    "RecommendationPriority",
    "RecommendationType",
    "get_evolution_guide",
    # Learning Engine (MD-3021)
    "LearningEngine",
    "Experience",
    "ExperienceType",
    "ExperienceResult",
    "LearningOutcome",
    "SkillLevelData",
    "LearningStats",
    "LearningEngineConfig",
    "get_learning_engine",
    # Evolution Tracker (MD-3021)
    "EvolutionTracker",
    "Milestone",
    "MilestoneType",
    "EvolutionSnapshot",
    "EvolutionStage",
    "GrowthMetrics",
    "EvolutionConfig",
    "get_tracker",
    "record_skill_update",
    "get_evolution_summary",
    # RAG Connector (MD-3026)
    "RAGConnector",
    "RAGConfig",
    "RAGProviderType",
    "QueryStrategy",
    "ConnectionStatus",
    "EmbeddingVector",
    "RetrievalResult",
    "RetrievalContext",
    "IndexStats",
    "get_rag_connector",
    "reset_rag_connector",
    "retrieve_context",
    # Context Enhancer (MD-3026)
    "ContextEnhancer",
    "EnhancerConfig",
    "EnhancementStrategy",
    "ContextFormat",
    "EnhancementPriority",
    "ContextChunk",
    "EnhancedPrompt",
    "EnhancedResponse",
    "get_context_enhancer",
    "reset_context_enhancer",
    "enhance_prompt",
    # Knowledge Index (MD-3026)
    "KnowledgeIndexManager",
    "IndexConfig",
    "IndexStatus",
    "Document",
    "DocumentType",
    "DocumentChunk",
    "IndexedDocument",
    "IndexingResult",
    "IndexHealth",
    "ChunkingStrategy",
    "get_knowledge_index_manager",
    "reset_knowledge_index_manager",
    "quick_index",
    # Memory Store (MD-3090)
    "MemoryStore",
    "Memory",
    "MemoryType",
    "MemoryStatus",
    "MemoryStoreConfig",
    "MemoryQueryResult",
    "ConsolidationResult",
    "ConsolidationStrategy",
    "StoreStats",
    "HealthStatus",
    "get_memory_store",
    "reset_memory_store",
    "store_memory",
    "retrieve_memories",
]
