"""
EU AI Act Article 11 - Technical Documentation Module.

EPIC: MD-2159 - [Compliance] Technical Documentation

This package provides tools for creating EU AI Act Article 11
compliant technical documentation including:
- System architecture documentation
- Algorithm documentation
- Data flow diagrams
- Model cards
- Risk assessments
- Training procedure documentation

AI DISCLOSURE: This code was generated by AI (Claude) for EU AI Act compliance purposes.
"""

from .system_architecture import (
    SystemArchitectureGenerator,
    SystemComponent,
    IntegrationPoint,
    SystemArchitecture,
    ComponentType,
    RiskLevel,
    create_architecture_generator
)

from .algorithm_documentation import (
    AlgorithmDocumentationRegistry,
    AlgorithmDocumentation,
    AlgorithmInput,
    AlgorithmOutput,
    DecisionLogic,
    AlgorithmCategory,
    TransparencyLevel,
    create_algorithm_registry
)

from .data_flow_documentation import (
    DataFlowDocumentationSystem,
    DataEntity,
    DataFlow,
    DataProcessor,
    DataFlowDiagram,
    DataClassification,
    DataFlowDirection,
    ProcessingPurpose,
    create_data_flow_system
)

from .model_cards import (
    ModelCardRegistry,
    ModelCard,
    ModelMetrics,
    BiasAssessment,
    UsageGuideline,
    ModelProvider,
    ModelCapability,
    BiasCategory,
    create_model_card_registry
)

from .risk_assessment import (
    AIRiskAssessmentSystem,
    RiskAssessment,
    RiskIdentification,
    RiskAnalysis,
    RiskMitigation,
    RiskCategory,
    RiskDomain,
    Likelihood,
    Impact,
    create_risk_assessment_system
)

from .training_procedures import (
    TrainingDocumentationSystem,
    TrainingDocumentation,
    TrainingDataset,
    TrainingProcedure,
    PromptTemplate,
    TrainingType,
    DataSourceType,
    DataQualityLevel,
    create_training_documentation_system
)

__all__ = [
    # System Architecture
    "SystemArchitectureGenerator",
    "SystemComponent",
    "IntegrationPoint",
    "SystemArchitecture",
    "ComponentType",
    "RiskLevel",
    "create_architecture_generator",

    # Algorithm Documentation
    "AlgorithmDocumentationRegistry",
    "AlgorithmDocumentation",
    "AlgorithmInput",
    "AlgorithmOutput",
    "DecisionLogic",
    "AlgorithmCategory",
    "TransparencyLevel",
    "create_algorithm_registry",

    # Data Flow Documentation
    "DataFlowDocumentationSystem",
    "DataEntity",
    "DataFlow",
    "DataProcessor",
    "DataFlowDiagram",
    "DataClassification",
    "DataFlowDirection",
    "ProcessingPurpose",
    "create_data_flow_system",

    # Model Cards
    "ModelCardRegistry",
    "ModelCard",
    "ModelMetrics",
    "BiasAssessment",
    "UsageGuideline",
    "ModelProvider",
    "ModelCapability",
    "BiasCategory",
    "create_model_card_registry",

    # Risk Assessment
    "AIRiskAssessmentSystem",
    "RiskAssessment",
    "RiskIdentification",
    "RiskAnalysis",
    "RiskMitigation",
    "RiskCategory",
    "RiskDomain",
    "Likelihood",
    "Impact",
    "create_risk_assessment_system",

    # Training Procedures
    "TrainingDocumentationSystem",
    "TrainingDocumentation",
    "TrainingDataset",
    "TrainingProcedure",
    "PromptTemplate",
    "TrainingType",
    "DataSourceType",
    "DataQualityLevel",
    "create_training_documentation_system",
]
