"""
EU AI Act Article 11 - Algorithm Documentation.

EPIC: MD-2159 - [Compliance] Technical Documentation
AC-2: Document all AI decision-making algorithms

This module provides structures and tools for documenting
AI decision-making algorithms per EU AI Act requirements.

AI DISCLOSURE: This code was generated by AI (Claude) for EU AI Act compliance purposes.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional, Any
import json


class AlgorithmCategory(Enum):
    """Categories of AI algorithms per EU AI Act."""
    CLASSIFICATION = "classification"
    GENERATION = "generation"
    RECOMMENDATION = "recommendation"
    PREDICTION = "prediction"
    OPTIMIZATION = "optimization"
    EXTRACTION = "extraction"


class TransparencyLevel(Enum):
    """Transparency levels for algorithms."""
    FULLY_EXPLAINABLE = "fully_explainable"
    PARTIALLY_EXPLAINABLE = "partially_explainable"
    BLACK_BOX = "black_box"


@dataclass
class AlgorithmInput:
    """Describes an input to an algorithm."""
    name: str
    data_type: str
    description: str
    required: bool
    pii_indicator: bool = False
    validation_rules: List[str] = field(default_factory=list)


@dataclass
class AlgorithmOutput:
    """Describes an output from an algorithm."""
    name: str
    data_type: str
    description: str
    confidence_available: bool = False
    explanation_available: bool = False


@dataclass
class DecisionLogic:
    """Documents the decision-making logic of an algorithm."""
    description: str
    decision_factors: List[str]
    weighting_explanation: str
    threshold_values: Dict[str, float]
    fallback_behavior: str


@dataclass
class AlgorithmDocumentation:
    """Complete documentation for an AI algorithm."""
    id: str
    name: str
    version: str
    category: AlgorithmCategory
    transparency_level: TransparencyLevel
    description: str
    purpose: str
    inputs: List[AlgorithmInput]
    outputs: List[AlgorithmOutput]
    decision_logic: DecisionLogic
    limitations: List[str]
    known_biases: List[str]
    performance_metrics: Dict[str, float]
    human_oversight_hooks: List[str]
    created_at: datetime
    updated_at: datetime
    author: str


class AlgorithmDocumentationRegistry:
    """
    Registry for managing AI algorithm documentation.

    Per EU AI Act Article 11, documentation must include:
    - Description of algorithmic logic
    - Design specifications and choices
    - Information about training approaches
    - Validation and testing procedures
    """

    def __init__(self):
        self.algorithms: Dict[str, AlgorithmDocumentation] = {}

    def register_algorithm(self, doc: AlgorithmDocumentation) -> bool:
        """Register an algorithm's documentation."""
        if doc.id in self.algorithms:
            return False
        self.algorithms[doc.id] = doc
        return True

    def get_algorithm(self, algorithm_id: str) -> Optional[AlgorithmDocumentation]:
        """Retrieve algorithm documentation by ID."""
        return self.algorithms.get(algorithm_id)

    def update_algorithm(self, algorithm_id: str, updates: Dict[str, Any]) -> bool:
        """Update an algorithm's documentation."""
        if algorithm_id not in self.algorithms:
            return False

        algo = self.algorithms[algorithm_id]
        for key, value in updates.items():
            if hasattr(algo, key):
                setattr(algo, key, value)
        algo.updated_at = datetime.utcnow()
        return True

    def list_algorithms(self, category: Optional[AlgorithmCategory] = None) -> List[AlgorithmDocumentation]:
        """List all algorithms, optionally filtered by category."""
        algorithms = list(self.algorithms.values())
        if category:
            algorithms = [a for a in algorithms if a.category == category]
        return algorithms

    def get_black_box_algorithms(self) -> List[AlgorithmDocumentation]:
        """Get algorithms with low transparency (requiring extra oversight)."""
        return [
            a for a in self.algorithms.values()
            if a.transparency_level == TransparencyLevel.BLACK_BOX
        ]

    def get_algorithms_with_pii(self) -> List[AlgorithmDocumentation]:
        """Get algorithms that process PII data."""
        result = []
        for algo in self.algorithms.values():
            if any(inp.pii_indicator for inp in algo.inputs):
                result.append(algo)
        return result

    def validate_documentation_completeness(self, algorithm_id: str) -> Dict[str, Any]:
        """Validate that algorithm documentation meets EU AI Act requirements."""
        algo = self.algorithms.get(algorithm_id)
        if not algo:
            return {"valid": False, "errors": ["Algorithm not found"]}

        issues = []

        # Check required fields
        if not algo.description or len(algo.description) < 50:
            issues.append("Description too short (min 50 chars)")

        if not algo.purpose:
            issues.append("Purpose not documented")

        if len(algo.inputs) == 0:
            issues.append("No inputs documented")

        if len(algo.outputs) == 0:
            issues.append("No outputs documented")

        if not algo.decision_logic.description:
            issues.append("Decision logic not documented")

        if len(algo.limitations) == 0:
            issues.append("Limitations not documented")

        if len(algo.known_biases) == 0:
            issues.append("Known biases not assessed (add 'None identified' if applicable)")

        if len(algo.human_oversight_hooks) == 0 and algo.transparency_level == TransparencyLevel.BLACK_BOX:
            issues.append("Black-box algorithm requires human oversight hooks")

        return {
            "valid": len(issues) == 0,
            "algorithm_id": algorithm_id,
            "issues": issues,
            "completeness_score": max(0, 100 - len(issues) * 12.5)
        }

    def generate_compliance_report(self) -> Dict[str, Any]:
        """Generate compliance report for all documented algorithms."""
        results = []
        for algo_id in self.algorithms:
            validation = self.validate_documentation_completeness(algo_id)
            results.append(validation)

        total = len(results)
        compliant = sum(1 for r in results if r["valid"])

        return {
            "total_algorithms": total,
            "compliant": compliant,
            "non_compliant": total - compliant,
            "compliance_rate": (compliant / total * 100) if total > 0 else 0,
            "black_box_count": len(self.get_black_box_algorithms()),
            "pii_processing_count": len(self.get_algorithms_with_pii()),
            "details": results,
            "generated_at": datetime.utcnow().isoformat()
        }

    def export_to_json(self) -> str:
        """Export all algorithm documentation to JSON."""
        data = []
        for algo in self.algorithms.values():
            data.append({
                "id": algo.id,
                "name": algo.name,
                "version": algo.version,
                "category": algo.category.value,
                "transparency": algo.transparency_level.value,
                "description": algo.description,
                "purpose": algo.purpose,
                "inputs": [{"name": i.name, "type": i.data_type, "pii": i.pii_indicator} for i in algo.inputs],
                "outputs": [{"name": o.name, "type": o.data_type} for o in algo.outputs],
                "limitations": algo.limitations,
                "known_biases": algo.known_biases,
                "performance": algo.performance_metrics,
                "oversight_hooks": algo.human_oversight_hooks
            })
        return json.dumps({"algorithms": data, "count": len(data)}, indent=2)


def create_algorithm_registry() -> AlgorithmDocumentationRegistry:
    """Factory function to create an AlgorithmDocumentationRegistry."""
    return AlgorithmDocumentationRegistry()
