"""
EU AI Act Article 11 - Data Flow Documentation.

EPIC: MD-2159 - [Compliance] Technical Documentation
AC-3: Create data flow diagrams (DFD)

This module provides tools for documenting data flows through
AI systems, including PII handling and retention policies.

AI DISCLOSURE: This code was generated by AI (Claude) for EU AI Act compliance purposes.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional, Any, Set
import json


class DataClassification(Enum):
    """Data classification levels per GDPR/EU AI Act."""
    PUBLIC = "public"
    INTERNAL = "internal"
    CONFIDENTIAL = "confidential"
    RESTRICTED = "restricted"
    PII = "pii"
    SENSITIVE_PII = "sensitive_pii"


class DataFlowDirection(Enum):
    """Direction of data flow."""
    INBOUND = "inbound"
    OUTBOUND = "outbound"
    INTERNAL = "internal"
    BIDIRECTIONAL = "bidirectional"


class ProcessingPurpose(Enum):
    """Lawful basis for data processing per GDPR."""
    CONSENT = "consent"
    CONTRACT = "contract"
    LEGAL_OBLIGATION = "legal_obligation"
    VITAL_INTERESTS = "vital_interests"
    PUBLIC_TASK = "public_task"
    LEGITIMATE_INTERESTS = "legitimate_interests"


@dataclass
class DataEntity:
    """Represents a data entity in the system."""
    id: str
    name: str
    classification: DataClassification
    description: str
    fields: List[str]
    pii_fields: List[str] = field(default_factory=list)
    retention_days: int = 365
    encryption_required: bool = False


@dataclass
class DataFlow:
    """Represents a data flow between entities."""
    id: str
    name: str
    source: str
    destination: str
    direction: DataFlowDirection
    data_entities: List[str]
    processing_purpose: ProcessingPurpose
    encryption_in_transit: bool
    logging_enabled: bool
    pii_masking: bool
    description: str


@dataclass
class DataProcessor:
    """Represents a component that processes data."""
    id: str
    name: str
    description: str
    input_entities: List[str]
    output_entities: List[str]
    transformations: List[str]
    ai_processing: bool = False
    human_oversight: bool = False


@dataclass
class DataFlowDiagram:
    """Complete Data Flow Diagram documentation."""
    id: str
    name: str
    version: str
    entities: List[DataEntity]
    flows: List[DataFlow]
    processors: List[DataProcessor]
    created_at: datetime
    updated_at: datetime
    author: str
    compliance_notes: List[str]


class DataFlowDocumentationSystem:
    """
    System for documenting data flows per EU AI Act Article 11.

    Requirements covered:
    - Data lineage and provenance
    - PII handling documentation
    - Data retention policies
    - Processing purpose documentation
    """

    def __init__(self, diagram_name: str):
        self.diagram_name = diagram_name
        self.entities: Dict[str, DataEntity] = {}
        self.flows: Dict[str, DataFlow] = {}
        self.processors: Dict[str, DataProcessor] = {}
        self.version = "1.0.0"
        self.created_at = datetime.utcnow()

    def add_entity(self, entity: DataEntity) -> bool:
        """Add a data entity to the diagram."""
        if entity.id in self.entities:
            return False
        self.entities[entity.id] = entity
        return True

    def get_entity(self, entity_id: str) -> Optional[DataEntity]:
        """Retrieve a data entity by ID."""
        return self.entities.get(entity_id)

    def add_flow(self, flow: DataFlow) -> bool:
        """Add a data flow to the diagram."""
        # Validate source and destination exist
        if flow.source not in self.entities and flow.source not in self.processors:
            return False
        if flow.destination not in self.entities and flow.destination not in self.processors:
            return False
        self.flows[flow.id] = flow
        return True

    def add_processor(self, processor: DataProcessor) -> bool:
        """Add a data processor to the diagram."""
        if processor.id in self.processors:
            return False
        self.processors[processor.id] = processor
        return True

    def list_entities(self, classification: Optional[DataClassification] = None) -> List[DataEntity]:
        """List all entities, optionally filtered by classification."""
        entities = list(self.entities.values())
        if classification:
            entities = [e for e in entities if e.classification == classification]
        return entities

    def get_pii_entities(self) -> List[DataEntity]:
        """Get all entities containing PII data."""
        return [
            e for e in self.entities.values()
            if e.classification in [DataClassification.PII, DataClassification.SENSITIVE_PII]
            or len(e.pii_fields) > 0
        ]

    def get_pii_flows(self) -> List[DataFlow]:
        """Get all flows that involve PII data."""
        pii_entity_ids = {e.id for e in self.get_pii_entities()}
        return [
            f for f in self.flows.values()
            if any(entity_id in pii_entity_ids for entity_id in f.data_entities)
        ]

    def validate_pii_handling(self) -> Dict[str, Any]:
        """Validate PII handling compliance."""
        issues = []
        pii_flows = self.get_pii_flows()

        for flow in pii_flows:
            if not flow.encryption_in_transit:
                issues.append({
                    "flow": flow.id,
                    "issue": "PII flow lacks encryption in transit"
                })
            if not flow.pii_masking:
                issues.append({
                    "flow": flow.id,
                    "issue": "PII flow lacks masking configuration"
                })
            if not flow.logging_enabled:
                issues.append({
                    "flow": flow.id,
                    "issue": "PII flow lacks audit logging"
                })

        return {
            "valid": len(issues) == 0,
            "pii_entity_count": len(self.get_pii_entities()),
            "pii_flow_count": len(pii_flows),
            "issues": issues
        }

    def get_data_lineage(self, entity_id: str) -> Dict[str, Any]:
        """Trace data lineage for an entity."""
        if entity_id not in self.entities:
            return {"error": "Entity not found"}

        upstream = []
        downstream = []

        for flow in self.flows.values():
            if entity_id in flow.data_entities:
                if flow.destination == entity_id or entity_id in flow.data_entities:
                    upstream.append({
                        "flow": flow.id,
                        "source": flow.source,
                        "purpose": flow.processing_purpose.value
                    })
                if flow.source == entity_id or entity_id in flow.data_entities:
                    downstream.append({
                        "flow": flow.id,
                        "destination": flow.destination,
                        "purpose": flow.processing_purpose.value
                    })

        return {
            "entity_id": entity_id,
            "upstream_sources": upstream,
            "downstream_destinations": downstream,
            "total_flows": len(upstream) + len(downstream)
        }

    def generate_dfd(self) -> DataFlowDiagram:
        """Generate the complete Data Flow Diagram documentation."""
        return DataFlowDiagram(
            id=f"dfd-{self.diagram_name.lower().replace(' ', '-')}",
            name=self.diagram_name,
            version=self.version,
            entities=list(self.entities.values()),
            flows=list(self.flows.values()),
            processors=list(self.processors.values()),
            created_at=self.created_at,
            updated_at=datetime.utcnow(),
            author="system",
            compliance_notes=self._generate_compliance_notes()
        )

    def _generate_compliance_notes(self) -> List[str]:
        """Generate compliance notes based on analysis."""
        notes = []
        pii_validation = self.validate_pii_handling()

        if pii_validation["pii_entity_count"] > 0:
            notes.append(f"System processes {pii_validation['pii_entity_count']} PII entities")

        if not pii_validation["valid"]:
            notes.append(f"WARNING: {len(pii_validation['issues'])} PII handling issues identified")

        ai_processors = [p for p in self.processors.values() if p.ai_processing]
        if ai_processors:
            notes.append(f"System has {len(ai_processors)} AI processing components")

        return notes

    def export_to_json(self) -> str:
        """Export the DFD to JSON format."""
        dfd = self.generate_dfd()
        return json.dumps({
            "id": dfd.id,
            "name": dfd.name,
            "version": dfd.version,
            "created_at": dfd.created_at.isoformat(),
            "updated_at": dfd.updated_at.isoformat(),
            "entity_count": len(dfd.entities),
            "flow_count": len(dfd.flows),
            "processor_count": len(dfd.processors),
            "pii_compliance": self.validate_pii_handling(),
            "compliance_notes": dfd.compliance_notes
        }, indent=2)


def create_data_flow_system(name: str = "Maestro AI Platform DFD") -> DataFlowDocumentationSystem:
    """Factory function to create a DataFlowDocumentationSystem."""
    return DataFlowDocumentationSystem(name)
