"""
EU AI Act Article 11 - System Architecture Documentation Generator.

EPIC: MD-2159 - [Compliance] Technical Documentation
AC-1: Create comprehensive system architecture document

This module generates and validates system architecture documentation
compliant with EU AI Act Article 11 requirements.

AI DISCLOSURE: This code was generated by AI (Claude) for EU AI Act compliance purposes.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional, Any
import json
import hashlib


class ComponentType(Enum):
    """Types of system components per EU AI Act classification."""
    AI_MODEL = "ai_model"
    DATA_PIPELINE = "data_pipeline"
    USER_INTERFACE = "user_interface"
    API_GATEWAY = "api_gateway"
    STORAGE = "storage"
    MONITORING = "monitoring"
    HUMAN_OVERSIGHT = "human_oversight"


class RiskLevel(Enum):
    """EU AI Act risk categories."""
    UNACCEPTABLE = "unacceptable"
    HIGH = "high"
    LIMITED = "limited"
    MINIMAL = "minimal"


@dataclass
class SystemComponent:
    """Represents a component in the AI system architecture."""
    id: str
    name: str
    component_type: ComponentType
    description: str
    risk_level: RiskLevel
    inputs: List[str] = field(default_factory=list)
    outputs: List[str] = field(default_factory=list)
    dependencies: List[str] = field(default_factory=list)
    human_oversight_required: bool = False
    data_types_processed: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class IntegrationPoint:
    """Represents an integration between components."""
    id: str
    source_component: str
    target_component: str
    data_flow_type: str
    encryption_required: bool
    pii_handling: bool
    description: str


@dataclass
class SystemArchitecture:
    """Complete system architecture document."""
    version: str
    created_at: datetime
    updated_at: datetime
    system_name: str
    system_description: str
    components: List[SystemComponent]
    integrations: List[IntegrationPoint]
    risk_assessment_summary: str
    human_oversight_mechanisms: List[str]
    compliance_status: Dict[str, bool]


class SystemArchitectureGenerator:
    """
    Generates EU AI Act compliant system architecture documentation.

    Per Article 11, technical documentation must include:
    - General description of the AI system
    - Detailed description of elements and development process
    - Information on monitoring, functioning and control
    """

    def __init__(self, system_name: str):
        self.system_name = system_name
        self.components: Dict[str, SystemComponent] = {}
        self.integrations: List[IntegrationPoint] = []
        self.version = "1.0.0"
        self.created_at = datetime.utcnow()

    def add_component(self, component: SystemComponent) -> bool:
        """Add a component to the architecture."""
        if component.id in self.components:
            return False
        self.components[component.id] = component
        return True

    def get_component(self, component_id: str) -> Optional[SystemComponent]:
        """Retrieve a component by ID."""
        return self.components.get(component_id)

    def add_integration(self, integration: IntegrationPoint) -> bool:
        """Add an integration point between components."""
        # Validate source and target exist
        if integration.source_component not in self.components:
            return False
        if integration.target_component not in self.components:
            return False
        self.integrations.append(integration)
        return True

    def list_components(self, component_type: Optional[ComponentType] = None) -> List[SystemComponent]:
        """List all components, optionally filtered by type."""
        components = list(self.components.values())
        if component_type:
            components = [c for c in components if c.component_type == component_type]
        return components

    def get_high_risk_components(self) -> List[SystemComponent]:
        """Get all components classified as high or unacceptable risk."""
        return [
            c for c in self.components.values()
            if c.risk_level in [RiskLevel.HIGH, RiskLevel.UNACCEPTABLE]
        ]

    def get_pii_handling_components(self) -> List[SystemComponent]:
        """Get components that process PII data."""
        return [
            c for c in self.components.values()
            if any("pii" in dt.lower() or "personal" in dt.lower()
                   for dt in c.data_types_processed)
        ]

    def validate_human_oversight(self) -> Dict[str, Any]:
        """Validate human oversight requirements per EU AI Act."""
        high_risk = self.get_high_risk_components()
        oversight_issues = []

        for component in high_risk:
            if not component.human_oversight_required:
                oversight_issues.append({
                    "component": component.id,
                    "issue": "High-risk component lacks human oversight flag",
                    "risk_level": component.risk_level.value
                })

        return {
            "valid": len(oversight_issues) == 0,
            "high_risk_count": len(high_risk),
            "issues": oversight_issues
        }

    def generate_architecture_document(self) -> SystemArchitecture:
        """Generate the complete architecture document."""
        oversight = self.validate_human_oversight()

        return SystemArchitecture(
            version=self.version,
            created_at=self.created_at,
            updated_at=datetime.utcnow(),
            system_name=self.system_name,
            system_description=f"AI System: {self.system_name}",
            components=list(self.components.values()),
            integrations=self.integrations,
            risk_assessment_summary=self._generate_risk_summary(),
            human_oversight_mechanisms=self._get_oversight_mechanisms(),
            compliance_status={
                "article_11_documentation": True,
                "human_oversight_validated": oversight["valid"],
                "risk_assessment_complete": True,
                "data_flow_documented": len(self.integrations) > 0
            }
        )

    def _generate_risk_summary(self) -> str:
        """Generate risk assessment summary."""
        risk_counts = {}
        for component in self.components.values():
            level = component.risk_level.value
            risk_counts[level] = risk_counts.get(level, 0) + 1

        return f"Risk Distribution: {json.dumps(risk_counts)}"

    def _get_oversight_mechanisms(self) -> List[str]:
        """Get list of human oversight mechanisms."""
        mechanisms = []
        for component in self.components.values():
            if component.human_oversight_required:
                mechanisms.append(f"{component.name}: Human override enabled")
        return mechanisms

    def export_to_json(self) -> str:
        """Export architecture to JSON format."""
        doc = self.generate_architecture_document()
        return json.dumps({
            "version": doc.version,
            "created_at": doc.created_at.isoformat(),
            "updated_at": doc.updated_at.isoformat(),
            "system_name": doc.system_name,
            "system_description": doc.system_description,
            "component_count": len(doc.components),
            "integration_count": len(doc.integrations),
            "risk_summary": doc.risk_assessment_summary,
            "human_oversight": doc.human_oversight_mechanisms,
            "compliance": doc.compliance_status
        }, indent=2)

    def get_document_hash(self) -> str:
        """Generate SHA-256 hash of the document for integrity verification."""
        content = self.export_to_json()
        return hashlib.sha256(content.encode()).hexdigest()


def create_architecture_generator(system_name: str = "Maestro AI Platform") -> SystemArchitectureGenerator:
    """Factory function to create a SystemArchitectureGenerator."""
    return SystemArchitectureGenerator(system_name)
